### ISSUE TITLE
[Feature Request] Command Line arguments

### ISSUE THREAD

**Issue by ZeptoBST** [schellingb/GamepadPhoenix#6]
Having the ability to launch games with GP through cmd would be great.

Something like: GamepadPhoenix.exe -g "nameofthegame"

**Comment by schellingb** [comment]
Hi there, thanks for using GP :-)
Just `GamepadPhoenix.exe "nameofthegame"` should already work.
Maybe that should be in the documentation :-)

**Comment by ZeptoBST** [comment]
My bad, I must have skipped that part of the documentation.
